### PR TITLE
fix: fix cache to prevent multiple concurrent refreshes

### LINKED ISSUE #427: Multiple calls to refreshCfg leak goroutines
## Bug Description

There can be multiple Goroutines waiting on [`refreshCertAfter`](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/v1.17.0/proxy/proxy/client.go#L230) for the same database instance. If [Dial](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/v1.17.0/proxy/proxy/client.go#L282) fails [tryConnect](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/v1.17.0/proxy/proxy/client.go#L284) of `cachedCfg` it calls `refreshCfg` which creates another Goroutine waiting `refreshCertAfter`.

It seems that each refreshing Goroutine will keep refreshing itself every hour and they only die off if they get limited by refreshCfg throttling.

We had misconfigured routing to the SQL instance's IP address. Requests to SQL instance worked sometimes and sometimes failed on [handshake](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/v1.17.0/proxy/proxy/client.go#L322).

Effectively this led to massive spam of `ephemeral certificate for instance x will expire soon, refreshing now.` in our logs after the service had run for an hour. There was no issue with ephemeral certificates but only with connection to the database.

In our case it was a configuration issue but a long-running `cloudsql-proxy` can ocassionally fail database connections and leak ephemeral certificate refreshes Goroutines. refreshCfg throttling gives some protection against this.

## How to reproduce

  1. Sometimes route Cloud SQL instance IP to wrong IP (or randomly fail [tryConnect ](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/v1.17.0/proxy/proxy/client.go#L297))
  2. Make database queries
  3. Wait for an hour to see multiple `ephemeral certificate for instance x will expire soon, refreshing now` log entries

## Environment

1. OS type and version: `golang:1.14-stretch` image
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.17.0

### PR DESCRIPTION
**Pull request by kurtisvg**
## Change Description

Expands on the behavior introduced in #666 by reconfiguring the `cachedCfg` function to prevent multiple simultaneous refreshes from occurring at once. 

## Checklist

- [ ] Make sure to open an issue as a 
  [bug/issue](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/new/choose) 
  before writing your code!  That way we can discuss the change, evaluate 
  designs, and agree on the general idea.
- [x] Ensure the tests and linter pass
- [x] Appropriate documentation is updated (if necessary)

## Relevant issues:

- Fixes #427

### CODE REVIEW

**Review by enocom — COMMENTED** [review]
Adding some initial comments. I have yet to load test this PR.

File: proxy/proxy/client.go [hunk 1]
```diff
@@ -292,33 +240,126 @@ func isExpired(cfg *tls.Config) bool {
...
+			timeToRefresh = certExpiration.Sub(now) - (5 * time.Second)
+			logging.Errorf("new ephemeral certificate expires sooner than expected (adjusting refresh time to compensate): current time: %v, certificate expires: %v", now, certExpiration)
+		}
+		go c.refreshCertAfter(instance, timeToRefresh)
+	}()
+	return done
+}
+
+// isValid returns true if the cacheEntry is still useable
+func isValid(c cacheEntry) bool {
```
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:286]: I generally prefer sticking with positive checks - go/tott-530

File: proxy/proxy/client.go [hunk 2]
```diff
@@ -292,33 +240,126 @@ func isExpired(cfg *tls.Config) bool {
...
+		}
+	}
+	return false
+}
+
+func (c *Client) cachedCfg(instance string) (string, *tls.Config, string, error) {
 	c.cacheL.RLock()
-	ret, ok := c.cfgCache[instance]
+
+	throttle := c.RefreshCfgThrottle
```
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:310]: tbh, I'm not sure. Both fields are under the `refreshCfgL` mutex, which makes me think they might be projected by it. However I'm now realizing they both are exported, which isn't great since the mutex isn't. 

They were previously inside a critical section, so I attempted to maintain the same here.

File: proxy/proxy/client.go [hunk 3]
```diff
@@ -292,33 +240,126 @@ func isExpired(cfg *tls.Config) bool {
...
+			lastRefreshed: time.Now(),
+			err:           err,
+			addr:          addr,
+			version:       ver,
+			cfg:           cfg,
+			done:          done,
+		}
+		c.cacheL.Unlock()
+
+		certExpiration := cfg.Certificates[0].Leaf.NotAfter
```
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:269]: I'm not sure I understand what your suggestion is. Are you suggesting moving it into `refreshCfg` or just scoping to `startRefresh`? 

You don't want to move it into `refreshCfg`, because you want to update the cacheEntry and schedule the refresh again, regardless of how the last operation went.

You don't want it to move scope up into `startRefresh` because you don't have the results of the refresh operation yet.

File: proxy/proxy/client.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (enocom) [reply proxy/proxy/client.go:287]: Interesting. TIL.

File: proxy/proxy/client.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (enocom) [reply proxy/proxy/client.go:312]: Based on internal usage in this file, I see no other writes to these fields. I suspect these fields are intended to be supplied when the `Client` is created and not modified later. But since they're exported, I suppose it's possible they could be changed later.

File: proxy/proxy/client.go [hunk 4]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
+		now := time.Now()
+		timeToRefresh := certExpiration.Sub(now) - refreshCfgBuffer
+		if timeToRefresh <= 0 {
+			// If a new certificate expires before our buffer has expired,
+			// we should wait a bit and schedule a new refresh to much closer to the expiration's date
+			// TODO: This situation probably only occurs for Issue #622 - when the oauth2 token isn't refreshed before the cert is
```
Comment (enocom) [inline proxy/proxy/client.go:276]: Could we revert #680 with the code that follows?

File: proxy/proxy/client.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (enocom) [reply proxy/proxy/client.go:270]: I understand this code better now. Let me pose a different question below. Resolving.

File: proxy/proxy/client.go [hunk 5]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
+			timeToRefresh = certExpiration.Sub(now) - (5 * time.Second)
+			logging.Errorf("new ephemeral certificate expires sooner than expected (adjusting refresh time to compensate): current time: %v, certificate expires: %v", now, certExpiration)
+		}
+		logging.Infof("Scheduling refresh of ephemeral certifcate in %s", timeToRefresh)
+		go c.refreshCertAfter(instance, timeToRefresh)
```
Comment (enocom) [inline proxy/proxy/client.go:281]: Does this have to happen in a separate goroutine? I think we might be able to inline the function here and run it as part of the same goroutine. We'd need to close `done` on line 268 to do that.

File: proxy/proxy/client.go [hunk 6]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
 	return time.Now().After(cfg.Certificates[0].Leaf.NotAfter)
 }
 
-func (c *Client) cachedCfg(instance string) (string, *tls.Config, string) {
+// startRefresh kicks off a refreshCfg asynchronously, returning a channel that is closed
```
Comment (enocom) [inline proxy/proxy/client.go:244]: nit: returning a channel and updating the cacheEntry when it's complete.

File: proxy/proxy/client.go [hunk 7]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
+		}
+		c.cacheL.Unlock()
+	}
 
-	// Don't waste time returning an expired/invalid cert.
-	if !ok || ret.err != nil || isExpired(ret.cfg) {
-		return "", nil, ""
+	if !isValid(e) {
+		// if the previous result was invalid, wait for the next result to complete
+		// TODO: Ask for context?
```
Comment (enocom) [inline proxy/proxy/client.go:347]: What do you mean with this TODO?

File: proxy/proxy/client.go [hunk 8]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
-		}
-	}
-
-	addr, cfg, _, err := c.refreshCfg(instance)
+	addr, cfg, _, err := c.cachedCfg(instance)
 	if err != nil {
 		return nil, err
 	}
+
+	// TODO: attempt an early refresh if an connect fails?
```
Comment (enocom) [inline proxy/proxy/client.go:366]: I think we can hold off on this for now until we better understand how this code performs generally.

File: proxy/proxy/client.go [hunk 9]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
+	go func() {
+		defer close(done)
+		addr, cfg, ver, err := c.refreshCfg(instance)
+
+		c.cacheL.Lock()
+		old := c.cfgCache[instance]
+		// if we failed to refresh cfg do not throw out potentially valid one
+		if err != nil && !isExpired(old.cfg) {
+			logging.Errorf("failed to refresh the ephemeral certificate for %s, returning previous cert instead: %v", instance, err)
+			addr, cfg, ver, err = old.addr, old.cfg, old.version, old.err
```
Comment (enocom) [inline proxy/proxy/client.go:258]: In this case, do we know `old.err` to be nil? If so, it would be better to assign `err` to `nil` directly.

File: proxy/proxy/client.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (enocom) [reply proxy/proxy/client.go:287]: Actually, reading the link above, I see it says, "If your conditional looks like “if not … else …” then reverse it to put the positive case first.".

That makes me think we flip the method to `isInvalid`, or to stick with a positive phrasing, `isStale`, or `isErred`, etc. That way we write `if isStale` instead of requiring readers to parse `if !isValid`, which requires a little more mental effort to understand.

**Review by enocom — COMMENTED** [review]
I've read through the original carefully and now this PR. It's looking pretty good. I've added some additional comments.

I think we're on a good path here and after resolving the comments, we should load test this before cutting a new release, just to shake out any additional issues.

File: proxy/proxy/client.go (hunk 5 above)
Comment (enocom) [reply proxy/proxy/client.go:281]: If later calls to `tryConnect` fail, what stops this goroutine?

File: proxy/proxy/client.go [hunk 10]
```diff
@@ -292,33 +241,129 @@ func isExpired(cfg *tls.Config) bool {
...
+		// the state may have changed between critical sections, so double check
+		e = c.cfgCache[instance]
+		if needsRefresh(e, refreshCfgBuffer) {
+			if time.Since(e.lastRefreshed) >= throttle {
+				// start a new refresh and update the cachedEntry to reflect that
+				e.done = c.startRefresh(instance, refreshCfgBuffer)
+				e.lastRefreshed = time.Now()
+				c.cfgCache[instance] = e
+			} else {
+				// TODO: Should this be a returned error?
```
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:338]: I think we'd only want to send a throttled error if the existing entry is no longer useable, otherwise we may throttle and return valid results but also a non-nil err.  

I think for right now I'm going to leave this as is, since it's preserving the existing behavior. I'll leave the TODO and we can determine in the future if we wish to pursue.

File: proxy/proxy/client.go (hunk 4 above)
Comment (kurtisvg) [reply proxy/proxy/client.go:276]: What we discussed yesterday is the following two choices:

without #680:
```
55m - Refresh successfully but cert expires early - schedules a new one at 59:55s
59m:55s - Second refresh attempted. If it fails, cert will expire before next attempt. 
```
If successful, this doubles the sqladmin quota usage. 

With #680:
```
59m - Refresh. If failed, schedules a new one at 59:30s
```
Even if the first fails, we get 2 attempts (and a 3rd started) before the cert expires. Quota usage is as expected.

File: proxy/proxy/client.go (hunk 5 above)
Comment (kurtisvg) [reply proxy/proxy/client.go:281]: > Does this have to happen in a separate goroutine? I think we might be able to inline the function here and run it as part of the same goroutine.

This is easier to leave in a separate goroutine because the other options are:
1. iterate recursively -> (likely) eventual stack overflow
2. iterate in a loop -> would require a significant rewrite so that it can be started or terminated. I'd prefer to keep the existing logic outside of the caching mostly intact for now. 

> If later calls to tryConnect fail, what stops this goroutine?

The current logic is (simplified):
1. A happens to `cachedCfg`
2. If we need a new refresh, call `startRefresh`
3. `startRefresh` starts goroutine, performs a refresh, and schedules a call to `cachedCfg` 55 minutes in the future
4. `cachedCfg` is called again

The goroutine will terminate when `cachedCfg` is called. If it's called at the right time, it kicks off a new refresh. If it's called at the wrong time the next call to `cachedCfg` will determine if it needs to be started.  .

File: proxy/proxy/client.go (hunk 6 above)
Comment (kurtisvg) [reply proxy/proxy/client.go:244]: Not sure what this means. Can you clarify?

File: proxy/proxy/client.go (hunk 9 above)
Comment (kurtisvg) [reply proxy/proxy/client.go:258]: We don't know if `old.err` is `nil`. It doesn't really matter - if our current result failed, the old result is either good or bad. It's at least better than the current result.

File: proxy/proxy/client.go (hunk 4 above)
Comment (enocom) [reply proxy/proxy/client.go:276]: :+1:

File: proxy/proxy/client.go (hunk 6 above)
Comment (enocom) [reply proxy/proxy/client.go:244]: Just updating the doc string to read a little better.

**Review by enocom — APPROVED** [review]
My comments are mostly stylistic and aren't blocking.

File: proxy/proxy/client.go (hunk 7 above)
Comment (kurtisvg) [reply proxy/proxy/client.go:347]: Update cachedCfg to use a context arg (which I've just done).

File: proxy/proxy/client.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:287]: We're not using an `if not … else …`, we're just using an "if else", so that doesn't apply here. If we were, it would be better to put the `isValid` case first and then `!isValid` case second. 

The problem is that the "In" from "Invalid" is a negation, and if you ever need to inverse a negation you end up having a double negative to accomplish that (`!IsInvalid`). 

IMO, the summary wraps it up quite nicely:
>  in general checking the presence or absence of a positive is simpler for readers to understand than checking the presence or absence of a negative.

File: proxy/proxy/client.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (kurtisvg) [reply proxy/proxy/client.go:312]: Will play it safe and leave it for now - I don't think it's a significant performance difference.

**Review by enocom — APPROVED** [review]
LGTM.

Let's talk about l294 (i.e., `go c.refreshCartAfter`) offline.
