### PR TITLE
fix: verify TokenSource exists in TokenExpiration()

### LINKED ISSUE #640: Nil pointer dereference in TokenExpiration
## Bug Description

I'm using "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/postgres" embeded in a Go application within gorm. Previously used 1.19.2, now updated to 1.20.0. Not sure if it matters but setup is fairly simple, the path to the IAM credentials needed are provided via the environment variable. Now gives nil pointer dereference.
## Stacktrace
```
runtime error: invalid memory address or nil pointer dereference
```

## Location
Traced it down to `s.TokenSource` being nil:
```
func (s *RemoteCertSource) TokenExpiration() (ret time.Time, err error) {
	tok, err := s.TokenSource.Token()
	if err != nil {
		return ret, err
	}
	return tok.Expiry, nil
}
```

Stack:
```
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/certs.(*RemoteCertSource).TokenExpiration at certs.go:301
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).refreshCfg at client.go:237
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).DialContext at client.go:322
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.DialContext at dial.go:59
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.Dial at dial.go:65
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/postgres.dialer.Dial at hook.go:52
<autogenerated>:2
github.com/lib/pq.dial at conn.go:381
github.com/lib/pq.(*Connector).open at conn.go:316
github.com/lib/pq.DialOpen at conn.go:291
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/postgres.(*Driver).Open at hook.go:60
database/sql.dsnConnector.Connect at sql.go:707
<autogenerated>:2
database/sql.(*DB).conn at sql.go:1294
database/sql.(*DB).PingContext at sql.go:799
database/sql.(*DB).Ping at sql.go:817
gorm.io/gorm.Open at gorm.go:148
```
(sensitive parts removed)

### PR DESCRIPTION
**Pull request by kurtisvg**
## Change Description

Updates `TokenExpiration()` to return a zero value if TokenSource is unset.

## Checklist

- [x] Make sure to open an issue as a 
  [bug/issue](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/new/choose) 
  before writing your code!  That way we can discuss the change, evaluate 
  designs, and agree on the general idea.
- [x] Ensure the tests and linter pass
- [x] Appropriate documentation is updated (if necessary)

## Relevant issues:

- Fixes #640

### CODE REVIEW

**Review by enocom — APPROVED** [review]

File: proxy/certs/certs.go [hunk 1]
```diff
@@ -298,6 +298,10 @@ func (s *RemoteCertSource) Remote(instance string) (cert *x509.Certificate, addr
 
 // TokenExpiration returns the expiration time for token source associated with remote cert source.
 func (s *RemoteCertSource) TokenExpiration() (ret time.Time, err error) {
+	// if no token is being used, return zero for expiration
+	if s.TokenSource == nil {
+		return ret, err
```
Comment (enocom) [inline proxy/certs/certs.go:303]: Minor nit: Might be nice to remove the named return values while you're in here. But not a big deal.

**Comment by timcooijmans** [comment]
Fixes my issue! Thanks
