### PR TITLE
fix #157

### LINKED ISSUE #157: Improve error message when gcloud path missing
I had some trouble running the proxy in Grunt scripts and on CircleCI, eventually figured out that it was because the `PATH` environment variable was missing or didn't contain the google-cloud-sdk/bin directory.

The error is pretty cryptic, it would be helpful if it were more explicit.

**To reproduce**
1. Verify cloud_sql_proxy is working:

`./cloud_sql_proxy -dir=/cloudsql`

You should get output like

```
2018/04/14 20:38:48 Using gcloud's active project: your-project-12345
2018/04/14 20:38:53 Listening on /cloudsql/your-project-12345:us-central1:your-db/.s.PGSQL.5432 for your-project-12345:us-central1:your-db
2018/04/14 20:38:53 Ready for new connections
```

2. Rerun with google-cloud-sdk removed from path

`PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin ./cloud_sql_proxy -dir=/cloudsql`

Outputs
```
2018/04/14 20:38:31 must specify -projects, -fuse, or -instances
```

**Expected Behaviour**
When the google-cloud-sdk is missing from the path, it should give a friendlier message, like, say

```
2018/04/14 20:38:31 Cannot find google-cloud-sdk/bin, please ensure it is in the PATH
```

### PR DESCRIPTION
**Pull request by lychung83**
fix issue #157 by better error logging.

### CODE REVIEW

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 1]
```diff
@@ -328,15 +340,19 @@ func listInstances(ctx context.Context, cl *http.Client, projects []string) ([]s
 }
 
 func gcloudProject() []string {
+	const gcloudResultErrStr = "gcloud failed to get project list. See log for detail."
```
Comment (easwars) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go]: gcloudResultErrStr is unused.

File: cmd/cloud_sql_proxy/proxy.go [hunk 2]
```diff
@@ -338,10 +338,24 @@ func CreateInstanceConfigs(dir string, useFuse bool, instances []string, instanc
 	}
 	// FUSE disabled.
 	if len(instances) == 0 && instancesSrc == "" {
+		// Failure to specifying instance can be caused by following reasons.
+		// 1. not enough information is provided by flags
+		// 2. failed to invoke gcloud
+		var flags string
 		if fuse.Supported() {
-			return nil, errors.New("must specify -projects, -fuse, or -instances")
+			flags = "-projects, -fuse, or -instances"
```
Comment (easwars) [inline cmd/cloud_sql_proxy/proxy.go]: This should be 
flags = "-projects, -fuse, -instances or -instances_metadata"
and the line below should be 
flags = "-projects, -instances or -instances_metadata"

-instances_metadata was missing earlier as well, which was wrong I think.
