### PR TITLE
fix: strip monotonic clock reading during refresh

### LINKED ISSUE #1199: Certificate refresh cycle does not work with laptop sleep
## Question
What is the best way to set up Cloud SQL Proxy on MacOS for local access to databases? This is so that our engineering team can securely connected to our databases.

I currently have things set up using `launchd` and `launchctl`.

## Additional Context

As mentioned, I have things set up with `launchd` on MacOS.

The issue is that sometimes, the proxy does not refresh the certificate. This happens when laptops go to sleep and wake up after the refresh time:
```
2022/05/11 09:14:08 Scheduling refresh of ephemeral certificate in 59m3.548513709s
2022/05/11 09:14:15 ephemeral certificate for instance OUR_DATABASE will expire soon, refreshing now.
2022/05/11 09:14:15 refreshing ephemeral certificate for instance OUR_DATABASE
2022/05/11 09:14:15 Scheduling refresh of ephemeral certificate in 59m3.678916417s
2022/05/11 10:49:50 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:51 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:51 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:55 New connection for "OUR_DATABASE"
2022/05/11 10:49:56 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:50:01 New connection for "OUR_DATABASE"
2022/05/11 10:50:01 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:54:16 ephemeral certificate for instance athelas-staging:us-central1:athelas-staging will expire soon, refreshing now.
2022/05/11 10:54:16 refreshing ephemeral certificate for instance athelas-staging:us-central1:athelas-staging
2022/05/11 10:54:17 Scheduling refresh of ephemeral certificate in 59m3.524621084s
2022/05/11 10:54:23 ephemeral certificate for instance OUR_DATABASE will expire soon, refreshing now.
2022/05/11 10:54:23 refreshing ephemeral certificate for instance OUR_DATABASE
2022/05/11 10:54:23 Scheduling refresh of ephemeral certificate in 59m3.670461042s
2022/05/11 10:56:27 New connection for "OUR_DATABASE"
```
Notice how there was a refresh scheduled for 10:14, but it did not go through.

A possible solution is to have the launchd service restart on sleep/wake, but that isn't a feature of launchd and I'd prefer not to do that. Is this an issue with the proxy, Go, or MacOS?

### PR DESCRIPTION
**Pull request by enocom**
Removing the monotonic clock reading ensures the code is resilient when
waking from sleep (where the monotonic clock may be inaccurate for some
time).

Fixes #1199.

### CODE REVIEW

File: proxy/proxy/client.go [hunk 1]
```diff
@@ -377,7 +377,7 @@ func needsRefresh(e cacheEntry, refreshCfgBuffer time.Duration) bool {
 	if e.done == nil { // no refresh started
 		return true
 	}
-	if !isValid(e) || e.cfg.Certificates[0].Leaf.NotAfter.Sub(time.Now()) <= refreshCfgBuffer {
+	if !isValid(e) || e.cfg.Certificates[0].Leaf.NotAfter.Round(0).Sub(time.Now().Round(0)) <= refreshCfgBuffer {
```
Comment (kurtisvg) [inline proxy/proxy/client.go:380]: nit: Do we need to strip out of both? Shouldn't just 1 be enough?

**Review by kurtisvg — APPROVED** [review]

File: proxy/proxy/client.go (hunk 1 above)
Comment (enocom) [reply proxy/proxy/client.go:380]: I think we want to strip off the monotonic reading from both values if I'm reading this correctly: https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/time/time.go;l=848
