### PR TITLE
fix: ensure proxy shuts down gracefully on SIGTERM

### LINKED ISSUE #876: The proxy doesn't shutdown gracefully when running in fuse mode
When the proxy receives a SIGTERM, it [immediately exits](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/5dd6d25e5abd590990dd6237ec303516bb73b72a/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L658) preventing any of the `defer` statements registered in the main goroutine from running. In fuse mode this is particular egregious because the fuse mount is not cleaned up and has to be manually unmonuted.

### PR DESCRIPTION
**Pull request by enocom**
Fixes #876

### CODE REVIEW

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 1]
```diff
@@ -651,11 +652,10 @@ func main() {
 		}()
 
 		err := proxyClient.Shutdown(*termTimeout)
-		if err == nil {
-			os.Exit(0)
+		if err != nil {
+			logging.Errorf("Error during SIGTERM shutdown: %v", err)
+			os.Exit(1)
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:657]: This os.Exit here - does this still ensure `cancel()` is called?

Comment (enocom) [reply cmd/cloud_sql_proxy/cloud_sql_proxy.go:657]: I double checked and interestingly, no. A call to `os.Exit` exits immediately ignoring any defers.

Cf. https://stackoverflow.com/questions/27629380/how-to-exit-a-go-program-honoring-deferred-calls

**Comment by enocom** [comment]
This change ended up being larger than I expected. With the calls to os.Exit, we were actually failing to run any previous defer statements.

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 2]
```diff
@@ -666,5 +652,15 @@ func main() {
...
+	proxyClient.RunContext(ctx, connSrc)
+	if err, ok := <-shutdown; ok {
+		return err
+	}
+	return nil
+}
+
+func main() {
+	if err := startProxy(); err != nil {
+		os.Exit(1)
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:664]: Some of the other `os.Exits` return different error codes return a 2 - this would possible be a breaking change?

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 3]
```diff
@@ -650,12 +634,14 @@ func main() {
 			}
 		}()
 
+		cancel()
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:637]: If this is canceled before proxyClient.Shutdown, won't it end all of the connections that you've passed it to?

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 4]
```diff
@@ -442,29 +442,12 @@ func gcloudProject() ([]string, error) {
...
 }
 
-// Main executes the main function of the proxy, allowing it to be called from tests.
-//
-// Setting timeout to a value greater than 0 causes the process to panic after
-// that amount of time. This is to sidestep an issue where sending a Signal to
-// the process (via the SSH library) doesn't seem to have an effect, and
-// closing the SSH session causes the process to get leaked. This timeout will
-// at least cause the proxy to exit eventually.
-func Main(timeout time.Duration) {
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:452]: Main is exported, so this change is breaking as well?

**Review by kurtisvg — CHANGES_REQUESTED** [review]

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go (hunk 4 above)
Comment (enocom) [reply cmd/cloud_sql_proxy/cloud_sql_proxy.go:452]: Fortunately, the `main` package cannot be imported anywhere, so in this case, we're the only possible consumers of this function, and it's unused in test.

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go (hunk 2 above)
Comment (enocom) [reply cmd/cloud_sql_proxy/cloud_sql_proxy.go:664]: I'll update the `startProxy` function to return an exit code, to maintain the different error codes.

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go (hunk 3 above)
Comment (enocom) [reply cmd/cloud_sql_proxy/cloud_sql_proxy.go:637]: Yes it would. I suppose we should give clients `termTimeout` to close themselves, and then cancel the context after that warning. I'll make this run on function exit.

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 5]
```diff
@@ -650,12 +634,14 @@ func main() {
...
-		if err == nil {
-			os.Exit(0)
+		if err != nil {
+			logging.Errorf("Error during SIGTERM shutdown: %v", err)
+			shutdown <- 2
+			return
 		}
-		logging.Errorf("Error during SIGTERM shutdown: %v", err)
-		os.Exit(2)
+		close(shutdown)
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:644]: nit: should this be deferred earlier?

**Review by kurtisvg — APPROVED** [review]

**Comment by enocom** [comment]
Ran the linting manually.

**Review by kurtisvg — APPROVED** [review]

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go [hunk 6]
```diff
@@ -442,29 +442,12 @@ func gcloudProject() ([]string, error) {
...
-		go func() {
-			time.Sleep(timeout)
-			panic("timeout exceeded")
-		}()
-	}
-	main()
-}
-
-func main() {
+func startProxy() int {
```
Comment (kurtisvg) [inline cmd/cloud_sql_proxy/cloud_sql_proxy.go:445]: nit: This is probably more like `runProxy` since it doesn't return until complete

**Review by kurtisvg — APPROVED** [review]

File: cmd/cloud_sql_proxy/cloud_sql_proxy.go (hunk 6 above)
Comment (enocom) [reply cmd/cloud_sql_proxy/cloud_sql_proxy.go:445]: Done.
