### PR TITLE
fix: use new oauth2 token with cert refresh

### LINKED ISSUE #643: Getting "new ephemeral certificate expires too soon" message and having trouble connecting to database
Hi everyone, 

- Image we are using: gcr.io/cloudsql-docker/gce-proxy:latest
- Timeframe: it started today around 12pm EST
- All our services are running on Kubernetes

I am curious if anybody else using the "latest" tag has been experiencing the same issue today. It seems like randomly (usually around the hour if it's worth something), our app will start having issues connecting to the database. Looking at the Cloud SQL proxy logs, we are seeing a bunch of issues with certificates expiration date. More precisely, the message `new ephemeral certificate expires too soon` is confusing us. 
Happy to provide more details, not sure what else could be useful. 

Thank you! 

```
2021/02/26 21:00:29 New connection for "production-1309:us-east1:shard2-replica-1"
2021/02/26 21:00:29 Instance production-1309:us-east1:shard2-replica-1 closed connection
2021/02/26 21:00:30 New connection for "production-1309:us-east1:shard2"
2021/02/26 21:00:30 Throttling refreshCfg(production-1309:us-east1:shard2): it was only called 2.002305461s ago
2021/02/26 21:00:30 couldn't connect to "production-1309:us-east1:shard2": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:28.329082026 +0000 UTC m=+14319.539486369, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:31 New connection for "production-1309:us-east1:shard-01-01"
2021/02/26 21:00:31 Throttling refreshCfg(production-1309:us-east1:shard-01-01): it was only called 20.009054701s ago
2021/02/26 21:00:31 couldn't connect to "production-1309:us-east1:shard-01-01": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:11.548442034 +0000 UTC m=+14302.758846397, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:31 New connection for "production-1309:us-east1:shard2-replica-2"
2021/02/26 21:00:31 Instance production-1309:us-east1:shard2-replica-2 closed connection
2021/02/26 21:00:32 New connection for "production-1309:us-east1:shard-01-04"
2021/02/26 21:00:32 Instance production-1309:us-east1:shard-01-04 closed connection
2021/02/26 21:00:34 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:34 ephemeral certificate ({Certificate:[[48 130 3 167 48 130 2 143 160 3 2 1 2 2 4 48 233 4 77 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 48 129 148 49 45 48 43 6 3 85 4 46 19 36 101 99 55 54 49 98 101 55 45 99 54 51 97 45 52 100 53 50 45 57 56 51 100 45 51 97 50 102 51 99 99 49 98 54 100 101 49 64 48 62 6 3 85 4 3 19 55 71 111 111 103 108 101 32 67 108 111 117 100 32 83 81 76 32 83 105 103 110 105 110 103 32 67 65 32 112 114 111 100 117 99 116 105 111 110 45 49 51 48 57 58 109 121 115 113 108 45 105 110 102 114 97 49 20 48 18 6 3 85 4 10 19 11 71 111 111 103 108 101 44 32 73 110 99 49 11 48 9 6 3 85 4 6 19 2 85 83 48 30 23 13 50 49 48 50 50 54 50 48 53 57 51 52 90 23 13 50 49 48 50 50 54 50 50 48 48 51 52 90 48 59 49 22 48 20 6 3 85 4 3 19 13 99 108 111 117 100 115 113 108 45 117 115 101 114 49 20 48 18 6 3 85 4 10 19 11 71 111 111 103 108 101 44 32 73 110 99 49 11 48 9 6 3 85 4 6 19 2 85 83 48 130 1 34 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 130 1 15 0 48 130 1 10 2 130 1 1 0 236 29 141 239 103 54 205 120 199 4 221 216 106 181 144 168 250 124 145 53 94 99 231 217 117 36 233 170 226 50 131 54 229 106 76 87 237 216 3 154 168 93 33 36 236 133 5 156 2 161 185 11 171 70 200 138 151 95 21 199 171 239 184 137 246 157 97 93 203 63 6 148 124 129 33 135 144 148 27 182 114 58 222 232 147 192 62 237 48 73 97 96 24 41 201 245 151 136 129 20 61 68 209 125 203 109 187 10 101 240 115 195 46 20 52 204 119 243 151 49 123 83 188 203 150 147 17 150 33 66 9 243 136 119 100 85 13 226 157 13 253 215 10 255 142 235 2 65 24 51 220 149 65 244 192 31 130 183 188 48 213 121 125 142 245 9 65 104 232 62 237 245 19 106 186 40 54 13 5 142 226 206 244 178 104 198 131 197 116 143 50 168 151 236 8 201 104 200 6 102 75 193 240 43 235 17 236 82 57 206 94 102 147 60 31 84 189 74 107 59 72 153 200 187 209 249 118 207 147 213 200 240 213 119 210 97 131 127 66 142 186 200 200 119 141 107 246 197 79 133 132 109 31 36 67 195 2 3 1 0 1 163 89 48 87 48 9 6 3 85 29 19 4 2 48 0 48 74 6 3 85 29 17 4 67 48 65 129 48 99 108 111 117 100 115 113 108 64 112 114 111 100 117 99 116 105 111 110 45 49 51 48 57 46 105 97 109 46 103 115 101 114 118 105 99 101 97 99 99 111 117 110 116 46 99 111 109 160 13 6 1 85 160 8 3 6 0 13 0 0 0 0 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 3 130 1 1 0 180 2 8 21 232 172 12 75 114 175 184 13 138 235 88 93 26 141 79 69 4 69 52 214 200 41 137 224 44 45 34 103 15 5 213 122 170 184 33 240 89 1 85 99 52 56 135 45 34 164 56 217 16 45 37 251 216 230 164 197 234 249 246 95 81 19 42 34 90 181 161 40 61 95 87 87 47 147 150 116 2 216 8 205 27 98 250 10 127 154 245 96 63 71 124 180 3 237 14 53 73 173 36 249 66 133 232 249 206 244 41 196 153 213 6 72 224 248 31 82 117 22 93 134 106 87 214 39 14 253 86 194 57 96 169 138 221 171 236 212 209 162 122 172 53 182 3 15 33 174 20 253 199 16 237 104 184 28 101 1 242 23 147 146 1 173 52 114 225 175 215 12 196 214 187 226 28 72 224 139 240 32 197 41 245 121 27 244 126 184 40 24 159 72 188 224 10 80 114 210 33 2 211 162 230 250 163 169 212 216 58 209 219 112 228 158 89 109 195 180 107 161 177 138 206 112 67 183 79 123 235 92 191 138 224 161 247 65 87 253 114 225 94 187 45 140 179 213 49 222 107 221 114 1 103 5]] PrivateKey:0xc0000c2900 SupportedSignatureAlgorithms:[] OCSPStaple:[] SignedCertificateTimestamps:[] Leaf:0xc00035a000}) error: new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:34 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:34 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:34 Throttling refreshCfg(production-1309:us-east1:mysql-infra): it was only called 1.082061ms ago
2021/02/26 21:00:34 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:34 New connection for "production-1309:us-east1:shard-01-03"
2021/02/26 21:00:34 Instance production-1309:us-east1:shard-01-03 closed connection
2021/02/26 21:00:34 New connection for "production-1309:us-east1:shard2-replica-1"
2021/02/26 21:00:34 Instance production-1309:us-east1:shard2-replica-1 closed connection
2021/02/26 21:00:36 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:36 Throttling refreshCfg(production-1309:us-east1:mysql-infra): it was only called 2.001835618s ago
2021/02/26 21:00:36 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:36 New connection for "production-1309:us-east1:shard2-replica-2"
2021/02/26 21:00:36 Instance production-1309:us-east1:shard2-replica-2 closed connection
2021/02/26 21:00:37 New connection for "production-1309:us-east1:shard-01-04"
2021/02/26 21:00:37 Instance production-1309:us-east1:shard-01-04 closed connection
2021/02/26 21:00:37 New connection for "production-1309:us-east1:shard2"
2021/02/26 21:00:37 Throttling refreshCfg(production-1309:us-east1:shard2): it was only called 9.00421349s ago
2021/02/26 21:00:37 couldn't connect to "production-1309:us-east1:shard2": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:28.329082026 +0000 UTC m=+14319.539486369, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:37 New connection for "production-1309:us-east1:shard2"
2021/02/26 21:00:37 Throttling refreshCfg(production-1309:us-east1:shard2): it was only called 9.005004892s ago
2021/02/26 21:00:37 couldn't connect to "production-1309:us-east1:shard2": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:28.329082026 +0000 UTC m=+14319.539486369, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:38 New connection for "production-1309:us-east1:shard-01-01"
2021/02/26 21:00:38 Throttling refreshCfg(production-1309:us-east1:shard-01-01): it was only called 27.010633183s ago
2021/02/26 21:00:38 couldn't connect to "production-1309:us-east1:shard-01-01": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:11.548442034 +0000 UTC m=+14302.758846397, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:38 New connection for "production-1309:us-east1:shard-01-01"
2021/02/26 21:00:38 Throttling refreshCfg(production-1309:us-east1:shard-01-01): it was only called 27.011422574s ago
2021/02/26 21:00:38 couldn't connect to "production-1309:us-east1:shard-01-01": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:11.548442034 +0000 UTC m=+14302.758846397, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:39 New connection for "production-1309:us-east1:shard2"
2021/02/26 21:00:39 Throttling refreshCfg(production-1309:us-east1:shard2): it was only called 11.005985142s ago
2021/02/26 21:00:39 couldn't connect to "production-1309:us-east1:shard2": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:28.329082026 +0000 UTC m=+14319.539486369, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:39 New connection for "production-1309:us-east1:shard-01-03"
2021/02/26 21:00:39 Client closed local connection on 127.0.0.1:3311
2021/02/26 21:00:39 New connection for "production-1309:us-east1:shard2-replica-1"
2021/02/26 21:00:39 Instance production-1309:us-east1:shard2-replica-1 closed connection
2021/02/26 21:00:40 New connection for "production-1309:us-east1:shard-01-01"
2021/02/26 21:00:40 Throttling refreshCfg(production-1309:us-east1:shard-01-01): it was only called 29.012241968s ago
2021/02/26 21:00:40 couldn't connect to "production-1309:us-east1:shard-01-01": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:11.548442034 +0000 UTC m=+14302.758846397, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:41 New connection for "production-1309:us-east1:shard2-replica-2"
2021/02/26 21:00:41 Instance production-1309:us-east1:shard2-replica-2 closed connection
2021/02/26 21:00:42 New connection for "production-1309:us-east1:shard-01-04"
2021/02/26 21:00:42 Instance production-1309:us-east1:shard-01-04 closed connection
2021/02/26 21:00:43 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:43 Throttling refreshCfg(production-1309:us-east1:mysql-infra): it was only called 9.00349932s ago
2021/02/26 21:00:43 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:43 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:43 Throttling refreshCfg(production-1309:us-east1:mysql-infra): it was only called 9.004368981s ago
2021/02/26 21:00:43 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
2021/02/26 21:00:44 New connection for "production-1309:us-east1:shard-01-03"
2021/02/26 21:00:44 Instance production-1309:us-east1:shard-01-03 closed connection
2021/02/26 21:00:44 New connection for "production-1309:us-east1:shard2-replica-1"
2021/02/26 21:00:44 Instance production-1309:us-east1:shard2-replica-1 closed connection
2021/02/26 21:00:45 New connection for "production-1309:us-east1:mysql-infra"
2021/02/26 21:00:45 Throttling refreshCfg(production-1309:us-east1:mysql-infra): it was only called 11.005782846s ago
2021/02/26 21:00:45 couldn't connect to "production-1309:us-east1:mysql-infra": new ephemeral certificate expires too soon: current time: 2021-02-26 21:00:34.180250709 +0000 UTC m=+14325.390655090, certificate expires: 2021-02-26 21:01:54.421888165 +0000 UTC m=+14405.632292581
```

### PR DESCRIPTION
**Pull request by enocom**
When clients use IAM authorization, an OAuth2 token is inserted into the
local certificate. In a previous commit, that token could expire within
the configured buffer (i.e., 5 minutes), causing the proxy to fail to
refresh its configuration and to report that the "new ephemeral
certificate expires too soon." Because the code always checked the token
expiration and the certificate expiration, this bug would affect both
clients using IAM auth and clients *not* using it.

This commit ensures the token's expiration is only considered when IAM
auth has been enabled, and when it has been enabled, this commit
likewise ensures the token's expiration is well beyond the buffer.

Fixes #643.

### CODE REVIEW

File: proxy/certs/certs.go [hunk 1]
```diff
@@ -172,12 +172,22 @@ func backoffAPIRetry(desc, instance string, do func() error) error {
 	return err
 }
 
+func refreshToken(ts oauth2.TokenSource, tok1 *oauth2.Token) (*oauth2.Token, error) {
```
Comment (kurtisvg) [inline proxy/certs/certs.go:175]: nit: maybe just `tok` or `orig`?

File: proxy/certs/certs.go [hunk 2]
```diff
@@ -186,10 +196,17 @@ func (s *RemoteCertSource) Local(instance string) (ret tls.Certificate, err erro
 	createEphemeralRequest := sqladmin.SslCertsCreateEphemeralRequest{
 		PublicKey: pubKey,
 	}
+	// If IAM login is enabled, add the OAuth2 token into the ephemeral
+	// certificate request, always refreshing the token to ensure its expiration
+	// is far enough in the future.
```
Comment (kurtisvg) [inline proxy/certs/certs.go:201]: nit: I'd suggest separating the second part of this sentence and move it down to L207. (it doesn't seem relevant to the reader unless they go down that path)

File: proxy/proxy/client.go [hunk 3]
```diff
@@ -73,7 +75,7 @@ type Client struct {
 	// instances. This value is defined by the server-side code, but for now it
 	// should always be 3307.
 	Port int
-	// Required; specifies how certificates are obtained.
+	// Certs specifies how certificates are obtained.
```
Comment (kurtisvg) [inline proxy/proxy/client.go:78]: Why did we drop `Required` here?

File: proxy/proxy/client.go [hunk 4]
```diff
@@ -219,6 +221,25 @@ func (c *Client) refreshCfg(instance string) (addr string, cfg *tls.Config, vers
...
+		}
+	}
+	now := time.Now()
+	timeToRefresh := certExpiration.Sub(now) - refreshCfgBuffer
+	if timeToRefresh <= 0 {
+		err = fmt.Errorf("new ephemeral certificate expires too soon: current time: %v, certificate expires: %v", now, certExpiration)
+		logging.Errorf("ephemeral certificate (%+v) error: %v", mycert, err)
+		return "", nil, "", err
+	}
+	go c.refreshCertAfter(instance, timeToRefresh)
```
Comment (kurtisvg) [inline proxy/proxy/client.go:241]: Why move this up?

**Review by kurtisvg — APPROVED** [review]

File: proxy/certs/certs.go (hunk 1 above)
Comment (enocom) [reply proxy/certs/certs.go:175]: :+1:

File: proxy/certs/certs.go (hunk 2 above)
Comment (enocom) [reply proxy/certs/certs.go:201]: Sounds good.

File: proxy/proxy/client.go (hunk 3 above)
Comment (enocom) [reply proxy/proxy/client.go:78]: Go docs should start with the thing they're documenting, but since it's unrelated to the PR here, I'll just restore the original and we can address this some other time.

File: proxy/proxy/client.go (hunk 4 above)
Comment (enocom) [reply proxy/proxy/client.go:241]: Mostly as a convenience for reading, but I'll move it back down to make a smaller diff.

**Comment by enocom** [comment]
There are a few manual tests I want to run before merging this. I've also found the Gcloud Token Source in this library doesn't allow for token refresh, which I need to resolve as well.

**Comment by enocom** [comment]
I've confirmed the gcloud fix works. This is ready for review again.

**Review by kurtisvg — APPROVED** [review]
